name: Go

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -o cdner-${{ runner.os }} -v ./...

      - name: Test
        run: go test -v ./...
      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cdner-${{ runner.os }}
          path: ./cdner-${{ runner.os }}

      - name: upload data artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cdner-data
          path: ./data

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cdner-${{ runner.os }}

      - name: release-data
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cdner-data
