name: Go

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -o cdner-${{ matrix.os }} -v ./...

      - name: Test
        run: go test -v ./...
      # step6: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cdner-${{ matrix.os }}
          path: ./cdner-${{ matrix.os }}

      # step7: create release
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: cdner-${{github.ref}}-${{ matrix.os }}
